# **Numpy**

In [1]:
import numpy as np

In [2]:
#create an array
arr= np.array([[1,2,3], [4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
arr[0,1]

2

In [4]:
arr.shape

(2, 3)

In [9]:
a=np.array([[1,2,3], [4,5,6], [7,8,9]])
b=np.array([[7,8,9], [4,5,6], [1,2,3]])
a, b

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]), array([[7, 8, 9],
        [4, 5, 6],
        [1, 2, 3]]))

In [10]:
a+b

array([[ 8, 10, 12],
       [ 8, 10, 12],
       [ 8, 10, 12]])

In [11]:
a-b

array([[-6, -6, -6],
       [ 0,  0,  0],
       [ 6,  6,  6]])

In [12]:
a*b

array([[ 7, 16, 27],
       [16, 25, 36],
       [ 7, 16, 27]])

In [13]:
np.dot(a,b)

array([[ 18,  24,  30],
       [ 54,  69,  84],
       [ 90, 114, 138]])

In [14]:
np.cross(a,b)

array([[ -6,  12,  -6],
       [  0,   0,   0],
       [  6, -12,   6]])